In [49]:
import pandas as pd
import numpy as np

In [50]:
wc=pd.read_csv("Desktop/Womens Clothing E-Commerce Reviews.csv")
wc.head()

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [51]:
wc.shape

(23486, 11)

In [52]:
wc.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [53]:
wc.isnull().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [59]:
wc.fillna("0", inplace = True)

#type(m)

In [60]:
wc.Title.value_counts().sort_values(ascending=False).head(20)

0                   3810
Love it!             136
Beautiful             95
Love                  88
Love!                 84
Beautiful!            72
Beautiful dress       60
Love it               59
Gorgeous              53
Love this dress!      53
Cute top              52
Disappointed          51
Great dress           49
Perfect               49
Super cute            44
Adorable              43
Great top             42
Not for me            37
Runs small            36
Great top!            35
Name: Title, dtype: int64

In [61]:
top_20=[x for x in wc.Title.value_counts().sort_values(ascending=False).head(20).index]
#top_20

In [62]:
for x in top_20: 
    wc[x]=np.where(wc['Title']==x,1,0)
encoded = wc[["Title"]+top_20]
encoded

,Title,0,Love it!,Beautiful,Love,Love!,Beautiful!,Beautiful dress,Love it,Gorgeous,...,Cute top,Disappointed,Great dress,Perfect,Super cute,Adorable,Great top,Not for me,Runs small,Great top!
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Some major design flaws,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,My favorite buy!,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Flattering shirt,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Not for the very petite,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Cagrcoal shimmer fun,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,"Shimmer, surprisingly goes with lots",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,Flattering,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,Such a fun dress!,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,Dress looks like it's made of cheap material,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,Perfect!!!,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,Runs big,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,Pretty party dress with some issues,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,"Nice, but not for my body",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,"You need to be at least average height, or taller",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,Looks great with white pants,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,Super cute and cozy,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,Stylish and comfortable,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,"Cute, crisp shirt",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,I'm torn!,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,Not what it looks like,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,"Like it, but don't love it.",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,Versatile,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,Falls flat,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,Huge disappointment,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,"Loved, but returned",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,Great shirt!!!,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,Great layering piece,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23456,Flattering and lovely sweater dress,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23457,Adorable,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
23458,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23459,Perfect except slip,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23460,Such high hopes!,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23461,Comfortable but not super-flattering on me,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23462,Its okay,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23463,Comfy pants,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23464,Compliments,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23465,Falls nicely,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23466,Cute and comfy,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23467,Super flattering!,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23468,Sweet stripes,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23469,Comfy and cute,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23470,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23471,Awkward fit for me,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23472,Perfectly drapey,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23473,Perfect dress,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23474,Much better in person!,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23475,Cute dress,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23476,Cheeky!,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23477,Entrancing,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23478,Unflattering,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23479,What a fun piece!,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23480,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23481,Great dress for many occasions,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23482,Wish it was made of cotton,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23483,"Cute, but see through",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23484,"Very cute dress, perfect for summer parties an...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23485,Please make more like this one!,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [63]:
encoded.shape

(23486, 21)

In [64]:
encoded.iloc[:,1:21]

,0,Love it!,Beautiful,Love,Love!,Beautiful!,Beautiful dress,Love it,Gorgeous,Love this dress!,Cute top,Disappointed,Great dress,Perfect,Super cute,Adorable,Great top,Not for me,Runs small,Great top!
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23456,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23457,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
23458,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23459,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23460,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23461,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23462,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23463,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23464,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23465,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23466,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23467,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23468,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23469,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23470,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23471,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23472,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23473,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23474,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23475,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23476,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23477,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23478,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23479,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23480,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23481,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23482,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23483,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23484,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23485,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [66]:
data=pd.concat([wc,encoded],axis=1)
data.head()
#df = pd.concat([n, Y], axis=1)
# Dropping drive-wheels, make and engine-location columns as they are encoded
data.drop(['Title', 'Review Text', 'Division Name','Department Name','Class Name'], inplace=True, axis=1)
## # Viewing few rows of data
data.head()

,Unnamed: 0,Clothing ID,Age,Rating,Recommended IND,Positive Feedback Count,0,Love it!,Beautiful,Love,...,Cute top,Disappointed,Great dress,Perfect,Super cute,Adorable,Great top,Not for me,Runs small,Great top!
0,0,767,33,4,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1080,34,5,1,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,1077,60,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,1049,50,5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,847,47,5,1,6,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [68]:
input_data=data.drop(data.iloc[:,[3]], axis = 1)
input_data.head(5)

,Unnamed: 0,Clothing ID,Age,Recommended IND,Positive Feedback Count,0,Love it!,Beautiful,Love,Love!,...,Cute top,Disappointed,Great dress,Perfect,Super cute,Adorable,Great top,Not for me,Runs small,Great top!
0,0,767,33,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1080,34,1,4,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,1077,60,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,1049,50,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,847,47,1,6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [70]:
output_data=data.iloc[:,3:4]
output_data.head(5)

   Rating
0       4
1       5
2       3
3       5
4       5

In [71]:
from sklearn.preprocessing import scale

In [72]:
input_data=scale(input_data)
input_data

C:\Users\naresh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.

array([[-1.73197706, -0.74334818, -0.83054886, ..., -0.03972269,
        -0.03918139, -0.03863255],
       [-1.73182956,  0.79628898, -0.74911087, ..., -0.03972269,
        -0.03918139, -0.03863255],
       [-1.73168207,  0.78153208,  1.36827674, ..., -0.03972269,
        -0.03918139, -0.03863255],
       ...,
       [ 1.73168207,  0.91434423, -0.99342483, ..., -0.03972269,
        -0.03918139, -0.03863255],
       [ 1.73182956,  0.81596486, -1.23773878, ..., -0.03972269,
        -0.03918139, -0.03863255],
       [ 1.73197706,  0.91434423,  0.71677286, ..., -0.03972269,
        -0.03918139, -0.03863255]])

In [73]:
from sklearn.model_selection import train_test_split
input_data_train,input_data_test,output_data_train,output_data_test=train_test_split(input_data,output_data,test_size=0.2,random_state=0)

In [74]:
input_data_train.shape

(18788, 45)

In [76]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(input_data_train)
input_data_train = scaler.transform(input_data_train)
input_data_test = scaler.transform(input_data_test)

In [77]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=2)
classifier.fit(input_data_train,output_data_train)

C:\Users\naresh\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=2, p=2,
           weights='uniform')

In [78]:
output_data_pred=classifier.predict(input_data_test)
output_data_pred

array([5, 5, 3, ..., 1, 5, 5], dtype=int64)

In [83]:
import numpy as np

In [86]:
from sklearn.metrics import accuracy_score
accuracy_score(output_data_pred,output_data_test)

0.435291613452533

In [10]:
n.select_dtypes(include="object")
n

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,0,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,0,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [30]:
type(n)

pandas.core.frame.DataFrame

In [64]:
import pandas as pd
en=n.nlargest(10, ['Age'])
en.shape

(5, 11)

In [42]:
x=en.values
pd.DataFrame(x).head()

,0,1,2,3,4,5,6,7,8,9,10
0,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
1,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
2,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses
3,1,1080,34,0,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
4,0,767,33,0,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates

In [43]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x_3 = LabelEncoder()
x[:, 3] = labelencoder_x_3.fit_transform(x[:, 3])
labelencoder_x_4 = LabelEncoder()
x[:, 4] = labelencoder_x_4.fit_transform(x[:, 4])
labelencoder_x_8 = LabelEncoder()
x[:, 8] = labelencoder_x_8.fit_transform(x[:, 8])
labelencoder_x_9 = LabelEncoder()
x[:, 9] = labelencoder_x_9.fit_transform(x[:, 9])
labelencoder_x_10 = LabelEncoder()
x[:, 10] = labelencoder_x_10.fit_transform(x[:, 10])

onehotencoder = OneHotEncoder(categorical_features = "all")
X = onehotencoder.fit_transform(X).toarray()
X

C:\Users\naresh\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\naresh\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:382: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. The passed value of 'all' is the default and can simply be removed.
  DeprecationWarning)

array([[0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0.,
        1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
        0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1.,
        1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0.,
        0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.]])

In [44]:
type(X)

numpy.ndarray

In [46]:
Y=pd.DataFrame(X)
Y

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [48]:
df = pd.concat([n, Y], axis=1)
# Dropping drive-wheels, make and engine-location columns as they are encoded
df.drop(['Title', 'Review Text', 'Division Name','Department Name','Class Name'], inplace=True, axis=1)
# # Viewing few rows of data
df.head()

,Unnamed: 0,Clothing ID,Age,Rating,Recommended IND,Positive Feedback Count,0,1,2,3,...,33,34,35,36,37,38,39,40,41,42
0,0,767,33,4,1,0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1,1080,34,5,1,4,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2,1077,60,3,0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,3,1049,50,5,1,0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,4,847,47,5,1,6,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [49]:
input_data=df.drop(df.iloc[:,[0,3]], axis = 1)
input_data.head(2)

,Clothing ID,Age,Recommended IND,Positive Feedback Count,0,1,2,3,4,5,...,33,34,35,36,37,38,39,40,41,42
0,767,33,1,0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1080,34,1,4,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [50]:
output_data=df.iloc[:,3:4]
output_data.head(2)

   Rating
0       4
1       5

In [51]:
from sklearn.preprocessing import scale

In [52]:
input_data=scale(input_data)
input_data

C:\Users\naresh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.

array([[-1.50256525, -1.15842261,  0.5       , -0.79056942, -0.5       ,
        -0.5       ,  2.        , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       ,  2.        , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       ,  2.        , -0.81649658,
        -0.5       , -0.5       ,  2.        , -0.5       ,  2.        ,
        -0.5       , -0.5       , -0.5       ,  2.        , -0.5       ,
        -1.22474487,  2.        , -2.        ,  0.81649658, -0.5       ,
        -0.5       ,  0.81649658, -0.5       , -0.5       , -0.5       ,
         1.22474487, -0.5       , -0.5       , -0.5       ,  1.22474487,
        -0.5       , -0.5       ],
       [ 0.88475923, -1.0602512 ,  0.5       ,  0.79056942, -0.5       ,
        -0.5       , -0.5       ,  2.        , -0.5       , -0.5       ,
        -0.5       ,  2.        , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       ,  2.        , -0.5       , -0.81649658,
        -0.5       ,  2.        , -0.5       , -0.5       , -0.5       ,
         2.        , -0.5       , -0.5       , -0.5       , -0.5       ,
         0.81649658, -0.5       ,  0.5       ,  0.81649658, -0.5       ,
        -0.5       , -1.22474487,  2.        , -0.5       ,  2.        ,
        -0.81649658, -0.5       , -0.5       , -0.5       , -0.81649658,
        -0.5       ,  2.        ],
       [ 0.86187753,  1.4922054 , -2.        , -0.79056942, -0.5       ,
        -0.5       , -0.5       , -0.5       ,  2.        , -0.5       ,
         2.        , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       ,  2.        , -0.5       , -0.5       , -0.81649658,
         2.        , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       ,  2.        , -0.5       , -0.5       ,
         0.81649658, -0.5       ,  0.5       , -1.22474487, -0.5       ,
         2.        ,  0.81649658, -0.5       , -0.5       , -0.5       ,
        -0.81649658, -0.5       ,  2.        ,  2.        , -0.81649658,
        -0.5       , -0.5       ],
       [ 0.64831496,  0.51049132,  0.5       , -0.79056942, -0.5       ,
         2.        , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       , -0.5       , -0.5       ,  2.        , -0.5       ,
         2.        , -0.5       , -0.5       , -0.5       ,  1.22474487,
        -0.5       , -0.5       , -0.5       , -0.5       , -0.5       ,
        -0.5       ,  2.        , -0.5       , -0.5       , -0.5       ,
         0.81649658, -0.5       ,  0.5       , -1.22474487,  2.        ,
        -0.5       ,  0.81649658, -0.5       , -0.5       , -0.5       ,
         1.22474487, -0.5       , -0.5       , -0.5       ,  1.22474487,
        -0.5       , -0.5       ],
       [-0.89238647,  0.2159771 ,  0.5       ,  1.58113883,  2.        ,
        -0.5       , -0.5       , -0.5       , -0.5       ,  2.        ,
        -0.5       , -0.5       , -0.5       , -0.5       ,  2.        ,
        -0.5       , -0.5       , -0.5       , -0.5       ,  1.22474487,
        -0.5       , -0.5       , -0.5       ,  2.        , -0.5       ,
        -0.5       , -0.5       , -0.5       , -0.5       ,  2.        ,
        -1.22474487, -0.5       ,  0.5       ,  0.81649658, -0.5       ,
        -0.5       , -1.22474487, -0.5       ,  2.        , -0.5       ,
        -0.81649658,  2.        , -0.5       , -0.5       , -0.81649658,
         2.        , -0.5       ]])

In [53]:
from sklearn.model_selection import train_test_split
input_data_train,input_data_test,output_data_train,output_data_test=train_test_split(input_data,output_data,test_size=0.2,random_state=0)

In [63]:
input_data_train.shape

(4, 47)

In [54]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(input_data_train)

input_data_train = scaler.transform(input_data_train)
input_data_test = scaler.transform(input_data_test)

In [57]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=2)
classifier.fit(input_data_train,output_data_train)

C:\Users\naresh\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=2, p=2,
           weights='uniform')

In [59]:
output_data_pred=classifier.predict(input_data_test)
output_data_pred

array([5], dtype=int64)

In [61]:
len(input_data_test)

1

In [62]:
input_data_test

array([[ 1.06785071,  2.5056458 , -2.5       , -0.96225045, -0.57735027,
        -0.57735027, -0.57735027, -0.57735027,  2.5       , -0.57735027,
         2.5       , -0.57735027, -0.57735027, -0.57735027, -0.57735027,
        -0.57735027,  2.5       , -0.57735027, -0.57735027, -1.        ,
         2.5       , -0.57735027, -0.57735027, -0.57735027, -0.57735027,
        -0.57735027, -0.57735027,  2.5       , -0.57735027, -0.57735027,
         1.        , -0.57735027,  0.57735027, -1.73205081, -0.57735027,
         2.5       ,  1.        , -0.57735027, -0.57735027, -0.57735027,
        -1.        , -0.57735027,  2.5       ,  2.5       , -1.        ,
        -0.57735027, -0.57735027]])